### ISSUE TITLE
Python OpenCV problem

### ISSUE THREAD

**Issue by DBonbon** [joeVenner/control-3d-character-using-python#6]
I hope you could help me with a Python error message I didn't manage to resolve. 

I followed your steps and had the following error message:

  File "C:\Users\yrfri\Documents\Blender\vincent facial mocap\Vincent(1).blend\OpenCVAnimOperator.py", line 30, in <module>
  File "C:\Users\yrfri\Documents\Blender\vincent facial mocap\Vincent(1).blend\OpenCVAnimOperator.py", line 43, in OpenCVAnimOperator
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-r2ue8w6k\opencv_contrib\modules\face\src\facemarkLBF.cpp:487: error: (-5:Bad argument) No valid input file was given, please check the given filename. in function 'cv::face::FacemarkLBFImpl::loadModel'

I'm using Blender 2.91, Python 3.9 on my computer and Python 3.77 for Blender. I tried the Blender Python version to run promlt as administrator. 

Here is what I tried to do in order to resolve the issue:
- Updated or re-installed all applications (python, Blender...) 

- followed the exchange on your Youtube:
-  tried path name with \\, /, "", '', 
-  tried to modify:  self._cap = cv2.VideoCapture(0) into (1) and back to the original script. 
- verified that the file size is 55.5MP

The error message is the same. 
Any input would be highly appreciated, I',m really wish to experience your facial mocap. 
thanks

**Comment by joeVenner** [comment]
Hi Friend,

I am really happy to hear that you are interested in my small project, and i will do my best till we find a solution for this,

From what you said i think that you have the right model and nothing wrong with it,

But what i think is the reason behind this, is the path that you set for the model, cause the error output shows `bad argument`

What I recommend is to :

- Download the Model repo from [HERE](https://github.com/kurnianggoro/GSOC2017/archive/master.zip) & Extract the Data folder

- Go to `OpenCVAnimOperator.py`  Line `40` and set the full path to the model `lbfmodel.yaml`, in windows please double the backslash `\` 

**Ex** : Insted of "**C:\Users\Joe\data\lbfmodel.yaml**" put  "**C:\\\Users\\\Joe\\\data\\\lbfmodel.yaml**" if in linux  "./home/Joe/data/lbfmodel.yaml"

Please let me know if your issue is resolved, if not share with me the output error

Best regards,
Joe

**Comment by DBonbon** [comment]
Thanks so much for your answer... It did help... I was so happy to play with it, i.e. i  regressed to a mental age of 5...

**Comment by joeVenner** [comment]
Happy To help 💯
